PLUGIN_ROUTE_AUTHORIZE = "/oauth/authorize"
PLUGIN_ROUTE_CALLBACK = "/oauth/callback"
PLUGIN_ROUTE_REVOKE = "/oauth/revoke"
PLUGIN_ROUTE_FORMS = "/forms"
PLUGIN_ROUTE_FORM = "/forms/{form_id}"
PLUGIN_ROUTE_IMPORT_FORM = "/forms/{form_id}/import"
PLUGIN_ROUTE_FORM_RESPONSES = "/forms/{form_id}/responses"
PLUGIN_ROUTE_FORM_RESPONSE = "/forms/{form_id}/responses/{response_id}"
