#!/bin/bash
COMPOSE_PROJECT=bettercolledted_ci_test_${CI_JOB_ID:-local}
PROJECT_DIRECTORY="."
function down(){
        docker-compose --project-directory $PROJECT_DIRECTORY --project-name $COMPOSE_PROJECT down || true

}
function executeTest(){
#    docker-compose --project-directory $PROJECT_DIRECTORY --project-name $COMPOSE_PROJECT up -d mongodb
    # sleep 5
    # docker  exec  ${COMPOSE_PROJECT}_mongodb_1     mongosh "mongodb://root:root@mongodb:27017/bettercollected_backend" --authenticationDatabase admin /seed-data.js
#    docker-compose --project-directory $PROJECT_DIRECTORY --project-name $COMPOSE_PROJECT up -d  --build  backend
    docker-compose --project-directory $PROJECT_DIRECTORY --project-name $COMPOSE_PROJECT up --no-start  --build test
    docker start  -ai  ${COMPOSE_PROJECT}_test_1
}

down
(cd .ci && executeTest)
down
