#!/bin/bash

user_preference="$1"

# Array to hold selected services
services_to_start=("mongodb" "mongo-seed" "webapp" "nginx" "backend" "auth")

# Common docker function
function dockerup(){
  docker compose -f "docker-compose.deployment.yml" up --build -d "$@"
}

function dockerdown() {
docker compose -f "docker-compose.deployment.yml" down 
}

if [ "$user_preference" == both ]; then
    services=("integrations-typeform" "integrations-googleform")
    for service in "${services[@]}"; do
        services_to_start+=("$service")
    done
    dockerup "${services_to_start[@]}"
elif [ "$user_preference" == googleform ]; then
    services_to_start+=("integrations-googleform")
    dockerup "${services_to_start[@]}"
elif [ "$user_preference" == typeform ]; then
    services_to_start+=("integrations-typeform")
    dockerup "${services_to_start[@]}"
elif [ "$user_preference" == down ]; then
    dockerdown
else 
    dockerup "${services_to_start[@]}"
fi
