[project]
name = "csv-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosmtplib==5.1.0",
    "annotated-types==0.7.0",
    "anyio==4.12.1",
    "attrs==25.4.0",
    "blinker==1.9.0",
    "boto3==1.42.53",
    "botocore==1.42.53",
    "certifi==2026.1.4",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "cryptography==46.0.5",
    "dnspython==2.8.0",
    "ecs-logging==2.3.0",
    "elastic-apm==6.25.0",
    "email-validator==2.3.0",
    "exceptiongroup==1.3.1",
    "fastapi==0.129.0",
    "fastapi-mail==1.6.2",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.11",
    "jinja2==3.1.6",
    "jmespath==1.1.0",
    "markupsafe==3.0.3",
    "nexus-rpc==1.3.0",
    "outcome==1.3.0.post0",
    "protobuf==6.33.5",
    "pycparser==3.0",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
    "pydantic-settings==2.13.1",
    "pysocks==1.7.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "regex==2025.11.3",
    "requests==2.32.5",
    "s3transfer==0.16.0",
    "selenium==4.41.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "starlette==0.52.1",
    "temporalio==1.23.0",
    "trio==0.33.0",
    "trio-websocket==0.12.2",
    "types-protobuf==6.32.1.20251210",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.6.3",
    "websocket-client==1.9.0",
    "wrapt==2.1.1",
    "wsproto==1.3.2"
]
