version: '3.1'

networks:
  mongodb:
    external: true

services:
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: fVzphcZvrn9bLqCY

  backend:
    image: backend:0.1.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - mongodb
