[project]
name = "auth"
version = "0.1.0"
description = "This project was generated with fastapi-mvc."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "nabin6246", email = "nabin62246@gmail.com" },
]
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "fastapi-users[beanie,oauth]>=14.0.0",
    "dependency-injector>=4.45.0",
    "classy-fastapi>=0.6.0",
    "httpx>=0.27.0",
    "pyjwt>=2.10.0",
    "google-auth-oauthlib>=1.1.0",
    "google-api-python-client>=2.150.0",
    "fastapi-mail>=1.4.1",
    "stripe>=15.3.0",
    "sentry-sdk[fastapi]>=2.21.0",
    "loguru>=0.7.2",
    "elastic-apm>=6.23.0",
    "cryptography>=44.0.0",
    "requests>=2.32.3",
    "common",
    "pydantic-settings>=2.13.0",
    "motor>=3.6.0",

]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=6.0.0",
    "pytest-asyncio>=0.25.0",
    "black>=25.1.0",
    "pre-commit>=4.0.0",
    "mongomock-motor>=0.0.30",
]

[tool.uv]
managed = true

[tool.uv.sources]
common = { path = "../common" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
omit = [
    "auth/__main__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pass",
]
