import enum


class UserTagType(str, enum.Enum):
    NEW_USER: str = "NEW_USER"
    FORM_IMPORTED: str = "FORM_IMPORTED"
    WORKSPACE_HANDLE_CHANGE: str = "WORKSPACE_HANDLE_CHANGE"
    CUSTOM_DOMAIN_UPDATED: str = "CUSTOM_DOMAIN_UPDATED"
    GROUP_CREATED: str = "GROUP_CREATED"
    FORM_ADDED_TO_GROUP: str = "FORM_ADDED_TO_GROUP"
    DELETION_REQUEST_RECEIVED: str = "DELETION_REQUEST_RECEIVED"
    DELETION_REQUEST_PROCESSED: str = "DELETION_REQUEST_PROCESSED"
    CUSTOM_SLUG: str = "CUSTOM_SLUG"
