export enum FormBuilderConditionalLogicalOperator {
    AND = 'and',
    OR = 'or'
}

export enum FormBuilderConditionalComparison {
    CONTAINS = 'contains',
    DOES_NOT_CONTAIN = 'does_not_contain',
    IS_EQUAL = 'is_equal',
    IS_NOT_EQUAL = 'is_not_equal',
    STARTS_WITH = 'starts_with',
    ENDS_WITH = 'ends_with',
    IS_EMPTY = 'is_empty',
    IS_NOT_EMPTY = 'is_not_empty',
    GREATER_THAN = 'greater_than',
    LESS_THAN = 'less_than',
    GREATER_THAN_EQUAL = 'greater_than_equal',
    LESS_THAN_EQUAL = 'less_than_equal'
}

export enum FormBuilderConditionalAction {
    SHOW_FIELDS = 'show_fields',
    HIDE_FIELDS = 'hide_fields',
    ENABLE_FIELDS = 'enable_fields',
    DISABLE_FIELDS = 'disable_fields',
    REQUIRE_FIELDS = 'require_fields',
    CALCULATE_VALUES = 'calculate_values',
    JUMP_TO_PAGE = 'jump_to_page'
}

export enum FormBuilderItems {
    GROUP_BLOCK = 'GROUP_BLOCK',
    BLOCK = 'BLOCK',
    FORM_TITLE = 'FORM_TITLE',
    LABEL = 'LABEL',
    HEADING1 = 'HEADING1',
    HEADING2 = 'HEADING2',
    HEADING3 = 'HEADING3',
    SUB_HEADING1 = 'SUB_HEADING1',
    SUB_HEADING2 = 'SUB_HEADING2',
    SUB_HEADING3 = 'SUB_HEADING3',

    INPUT_TEXT = 'INPUT_TEXT',
    QUESTION_INPUT_TEXT = 'QUESTION_INPUT_TEXT',

    INPUT_NUMBER = 'INPUT_NUMBER',
    QUESTION_INPUT_NUMBER = 'QUESTION_INPUT_NUMBER',

    INPUT_PHONE_NUMBER = 'INPUT_PHONE_NUMBER',
    QUESTION_INPUT_PHONE_NUMBER = 'QUESTION_INPUT_PHONE_NUMBER',

    INPUT_LINK = 'INPUT_LINK',
    QUESTION_INPUT_LINK = 'QUESTION_INPUT_LINK',

    INPUT_EMAIL = 'INPUT_EMAIL',
    QUESTION_INPUT_EMAIL = 'QUESTION_INPUT_EMAIL',

    INPUT_DATE = 'INPUT_DATE',
    QUESTION_INPUT_DATE = 'QUESTION_INPUT_DATE',

    TEXTAREA = 'TEXTAREA',
    QUESTION_TEXTAREA = 'QUESTION_TEXTAREA',

    MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
    QUESTION_MULTIPLE_CHOICE = 'QUESTION_MULTIPLE_CHOICE',

    CHECKBOX = 'CHECKBOX',
    QUESTION_CHECKBOX = 'QUESTION_CHECKBOX',

    DROPDOWN = 'DROPDOWN',
    QUESTION_DROPDOWN = 'QUESTION_DROPDOWN',

    MULTI_SELECT = 'MULTI_SELECT',
    QUESTION_MULTI_SELECT = 'QUESTION_MULTI_SELECT',

    FILE_UPLOAD = 'FILE_UPLOAD',
    QUESTION_FILE_UPLOAD = 'QUESTION_FILE_UPLOAD',

    RATING = 'RATING',
    QUESTION_RATING = 'QUESTION_RATING',

    RANKING = 'RANKING',
    QUESTION_RANKING = 'QUESTION_RANKING',

    CODE = 'CODE',
    QUESTION_CODE = 'QUESTION_CODE',

    LINEAR_SCALE = 'LINEAR_SCALE',
    QUESTION_LINEAR_SCALE = 'QUESTION_LINEAR_SCALE',

    MATRIX = 'MATRIX',
    QUESTION_MATRIX = 'QUESTION_MATRIX',

    TABLE = 'TABLE',
    QUESTION_TABLE = 'QUESTION_TABLE',

    PDF = 'PDF',
    QUESTION_PDF = 'QUESTION_PDF',

    IMAGE = 'IMAGE',
    QUESTION_IMAGE = 'QUESTION_IMAGE',

    VIDEO = 'VIDEO',
    QUESTION_VIDEO = 'QUESTION_VIDEO',

    AUDIO = 'AUDIO',
    QUESTION_AUDIO = 'QUESTION_AUDIO',

    EMBED = 'EMBED',
    QUESTION_EMBED = 'QUESTION_EMBED',

    CALCULATED = 'CALCULATED',

    DIVIDER = 'DIVIDER',
    PAGE_BREAK = 'PAGE_BREAK',
    THANK_YOU_PAGE = 'THANK_YOU_PAGE',
    CONDITIONAL = 'CONDITIONAL'
}
