name: Build Docker Images

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        service:
          - auth
          - backend
          - integrations/google
          - integrations/typeform
          - webapp
          - temporal/worker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        env:
          SERVICE_TAG: ${{ matrix.service }}
        run: |
          SERVICE_TAG=${SERVICE_TAG//\//-}
          docker build -t bettercollected/${SERVICE_TAG}:${{ github.sha }} ${{ matrix.service }}
          docker push bettercollected/${SERVICE_TAG}:${{ github.sha }}

      - name: Add Nightly and Latest Tags
        env:
          SERVICE_TAG: ${{ matrix.service }}
        run: |
          SERVICE_TAG=${SERVICE_TAG//\//-}
          if [[ "${{ github.ref }}" = "refs/heads/develop" ]]; then
            docker tag bettercollected/${SERVICE_TAG}:${{ github.sha }} bettercollected/${SERVICE_TAG}:nightly
            docker push bettercollected/${SERVICE_TAG}:nightly
          fi
          if [[ "${{ github.ref }}" = "refs/heads/master" ]]; then
            docker tag bettercollected/${SERVICE_TAG}:${{ github.sha }} bettercollected/${SERVICE_TAG}:latest
            docker push bettercollected/${SERVICE_TAG}:latest
          fi
