name: Build Docker Images
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        service:
          - auth
          - backend
          - integrations/google
          - integrations/typeform
          - webapp
          - temporal/worker
        
    runs-on: ubuntu-latest
      
      steps:
          - name: Checkout code
            uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-docker@v2
              with:
                dockerfile: ${{ matrix.service }}/Dockerfile

            - name: Build Docker image
              run: |
                docker build -t my-docker-registry/${{ matrix.service }}:${{ github.sha }} ${{ matrix.service }}
                
                if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                  docker tag bettercollected/${{ matrix.service }}:${{ github.sha }} my-docker-registry/${{ matrix.service }}:nightly
                fi
                
                if [ "${{ github.ref }}" = "refs/heads/master" ]; then
                  docker tag bettercollected/${{ matrix.service }}:${{ github.sha }} my-docker-registry/${{ matrix.service }}:latest
                fi

            - name: Log in to Docker registry
              uses: docker/login-action@v1
              with:
                registry: docker.io
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push Docker image
              run: |
                docker push bettercollected/${{ matrix.service }}:${{ github.sha }}
                
                if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                  docker push bettercollected/${{ matrix.service }}:nightly
                fi
                
                if [ "${{ github.ref }}" = "refs/heads/master" ]; then
                  docker push bettercollected/${{ matrix.service }}:latest
                fi