name: Build and Deploy Form Builder V2

on:
  push:
    branches:
      - feature/slide-formbuilder

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker image
        id: docker_build
        run: |
          docker build -f webbuilder/Dockerfile -t bettercollected/webbuilder:${{ github.sha }} .
          docker push bettercollected/webbuilder:${{ github.sha }}
      - name: Add nightly tag
        run: |
          docker tag bettercollected/webbuilder:${{ github.sha }} bettercollected/webbuilder:nightly
          docker push bettercollected/webbuilder:nightly
          
  deploy-form-builder-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image
        id: docker-deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SIRETO_BASTION_HOST }}
          username: ${{ secrets.SIRETO_BASTION_USERNAME }}
          key: ${{ secrets.SIRETO_BASTION_SSH_KEY }}
          port: ${{ secrets.SIRETO_BASTION_PORT }}
          script: |
            DOCKER_HOST=${{ vars.DEVELOP_HOST }} docker service update --image bettercollected/webbuilder:${{ github.sha }}  ${{ vars.DEVELOP_STACK }}_webbuilder
